import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatInputModule,
  MatFormFieldModule,
  MatDatepickerModule,
  MatAutocompleteModule,
  MatListModule,
  MatSliderModule,
  MatCardModule,
  MatSelectModule,
  MatButtonModule,
  MatIconModule,
  MatNativeDateModule,
  MatSlideToggleModule,
  MatCheckboxModule,
  MatMenuModule,
  MatTabsModule,
  MatTooltipModule,
  MatSidenavModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatSnackBarModule,
  MatTableModule,
  MatGridListModule,
  MatToolbarModule,
  MatBottomSheetModule,
  MatExpansionModule,
  MatDividerModule,
  MatSortModule,
  MatStepperModule,
  MatChipsModule,
  MatPaginatorModule,
  MatDialogModule,
  MatRippleModule,
  MatRadioModule,
  MatTreeModule,
  MatButtonToggleModule,
  MAT_DATE_LOCALE,
  MatBadgeModule,
} from '@angular/material';

import { MAT_MOMENT_DATE_ADAPTER_OPTIONS } from '@angular/material-moment-adapter';

const MaterialModule = [
  MatInputModule,
  MatFormFieldModule,
  MatDatepickerModule,
  MatAutocompleteModule,
  MatListModule,
  MatSliderModule,
  MatCardModule,
  MatSelectModule,
  MatButtonModule,
  MatIconModule,
  MatNativeDateModule,
  MatSlideToggleModule,
  MatCheckboxModule,
  MatMenuModule,
  MatTabsModule,
  MatTooltipModule,
  MatSidenavModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatSnackBarModule,
  MatTableModule,
  MatGridListModule,
  MatToolbarModule,
  MatBottomSheetModule,
  MatExpansionModule,
  MatDividerModule,
  MatSortModule,
  MatStepperModule,
  MatChipsModule,
  MatPaginatorModule,
  MatDialogModule,
  MatRippleModule,
  MatRadioModule,
  MatTreeModule,
  MatButtonToggleModule,
  MatBadgeModule,
];

@NgModule({
  declarations: [],
  imports: [
    CommonModule, MaterialModule
  ],
  exports: [MaterialModule],
  providers: [
    { provide: MAT_DATE_LOCALE, useValue: 'en-GB' },
    { provide: MAT_MOMENT_DATE_ADAPTER_OPTIONS, useValue: { useUtc: true } },
  ],
})
export class AngularMaterialModule { }
